# Generated by Django 5.2.7 on 2025-11-25 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_song_artist_song_streams_count_album_song_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='streams_count',
        ),
        migrations.CreateModel(
            name='MonthlyStreamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('streams', models.PositiveIntegerField(default=0)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_streams', to='app.song')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('song', 'date')},
            },
        ),
    ]
