# Generated by Django 5.2.7 on 2025-11-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_song_streams_count_monthlystreamrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ubicacion',
            field=models.CharField(choices=[('Asia', 'Asia'), ('Africa', 'Africa'), ('America', 'America'), ('Europa', 'Europa'), ('Oceania', 'Oceania')], default='America', max_length=15),
        ),
    ]
