# Generated by Django 5.2.7 on 2025-11-25 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_perfil_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CANCION_REPRODUCCION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reproduccion', models.DateTimeField(auto_now_add=True)),
                ('listener', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reproductions_made', to='app.perfil')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproductions', to='app.song')),
            ],
            options={
                'ordering': ['-fecha_reproduccion'],
            },
        ),
    ]
