# Generated by Django 5.2.7 on 2025-11-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cancion_reproduccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.DurationField(blank=True, help_text='Duracion de la cancion (ej. HH:MM:SS o MM:SS)', null=True),
        ),
    ]
