# Generated by Django 5.2.7 on 2025-11-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_song_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_art_url',
            field=models.URLField(blank=True, default='/static/images/default_2.jpg', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='img_src',
            field=models.URLField(default='/static/images/default_1.jpg', max_length=500),
        ),
    ]
