# Generated by Django 5.2.7 on 2025-11-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_album_cover_art_url_alter_song_img_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='img_src',
            field=models.URLField(blank=True, default='/static/images/default_1.jpg', max_length=500, null=True),
        ),
    ]
