# Generated by Django 5.2.7 on 2025-11-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_playlist_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='estado_moderacion',
            field=models.CharField(choices=[('ok', 'OK'), ('alert', 'ALERT'), ('ban', 'BAN'), ('en_espera', 'En_espera')], default='OK', max_length=15),
        ),
    ]
