# Generated by Django 5.2.7 on 2025-11-26 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_perfil_estado_moderacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionGeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continente', models.CharField(max_length=15, unique=True)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'verbose_name_plural': 'Ubicaciones Geográficas',
            },
        ),
        migrations.CreateModel(
            name='REGISTRO_MODERADOR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='Reporte de Usuario', max_length=100)),
                ('action_status', models.CharField(choices=[('ok', 'OK'), ('alert', 'ALERT'), ('ban', 'BAN'), ('en_espera', 'En_espera')], default='En_espera', max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('moderador_emisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_taken', to='app.perfil', verbose_name='Moderador Emisor')),
                ('perfil_afectado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_history', to='app.perfil', verbose_name='Perfil Afectado')),
            ],
            options={
                'verbose_name': 'Registro de Moderación',
                'verbose_name_plural': 'Registros de Moderación',
                'ordering': ['-fecha'],
            },
        ),
        migrations.DeleteModel(
            name='alertaMODERADOR',
        ),
    ]
